import Head from "next/head"
import { Header } from "./Header"

export const PageLayout = ({ children }) => {
    return (
        <div>
            <div>
                <title>My Craz App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </div>
            <Header></Header>
            <main>
                {children}
            </main>
        </div >
    )
}